# Generated by Django 6.0 on 2026-01-04 23:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('apod', 'Astronomy Picture of the Day (NASA)'), ('wikipedia', 'Wikipedia Picture of the Day'), ('bing', 'Bing Picture of the Day')], db_index=True, help_text='Picture source identifier', max_length=50, unique=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this source is currently enabled and available to users')),
                ('display_name', models.CharField(blank=True, help_text='Custom display name (optional, defaults to source choice label)', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the source', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Source Configuration',
                'verbose_name_plural': 'Source Configurations',
                'ordering': ['source'],
            },
        ),
        migrations.CreateModel(
            name='PictureOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('apod', 'Astronomy Picture of the Day (NASA)'), ('wikipedia', 'Wikipedia Picture of the Day'), ('bing', 'Bing Picture of the Day')], db_index=True, help_text='Source of the picture', max_length=50)),
                ('date', models.DateField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('original_explanation', models.TextField()),
                ('media_type', models.CharField(default='image', max_length=20)),
                ('image_url', models.URLField(max_length=500)),
                ('hd_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('local_image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('image_height', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('image_size_bytes', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('simplified_explanation', models.TextField(blank=True, null=True)),
                ('processed_explanation', models.TextField(blank=True, help_text='Explanation with Wikipedia links embedded', null=True)),
                ('copyright', models.CharField(blank=True, max_length=255, null=True)),
                ('source_url', models.URLField(blank=True, help_text='Original source page URL', max_length=500, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Picture of the Day',
                'verbose_name_plural': 'Pictures of the Day',
                'ordering': ['-date', 'source'],
                'indexes': [models.Index(fields=['-date', 'source'], name='pictures_pi_date_3bc70f_idx'), models.Index(fields=['source', 'is_processed'], name='pictures_pi_source_b30c28_idx')],
                'unique_together': {('source', 'date')},
            },
        ),
    ]
